import React, { useMemo, useState } from 'react';
import { AuditEvent, AuditEventType, User, Role, ComplianceReport } from '../types';
import { generateComplianceReport } from '../services/demoAgentService';
import { ChartBarIcon, ShieldCheckIcon, ToolsIcon, UserCircleIcon, WarningIcon } from './icons';

interface AuditViewProps {
    auditLog: AuditEvent[];
    currentUser: User;
}

const StatCard: React.FC<{ title: string; value: number; icon: React.ReactNode }> = ({ title, value, icon }) => (
    <div className="bg-surface p-6 rounded-lg border border-gray-700 flex items-center space-x-4">
        <div className="bg-primary/20 p-3 rounded-lg">{icon}</div>
        <div>
            <p className="text-gray-400 text-sm font-medium">{title}</p>
            <p className="text-3xl font-bold text-white">{value}</p>
        </div>
    </div>
);

const EventTypePill: React.FC<{ type: AuditEventType }> = ({ type }) => {
    const typeStyles: Record<AuditEventType, string> = {
        [AuditEventType.USER_QUERY]: 'bg-blue-500/10 text-blue-400',
        [AuditEventType.TOOL_CALL_INITIATED]: 'bg-sky-500/10 text-sky-400',
        [AuditEventType.TOOL_CALL_COMPLETED]: 'bg-green-500/10 text-green-400',
        [AuditEventType.SECURITY_ALERT]: 'bg-red-500/10 text-red-400',
        [AuditEventType.APPROVAL_REQUESTED]: 'bg-yellow-500/10 text-yellow-400',
        [AuditEventType.APPROVAL_DECISION]: 'bg-orange-500/10 text-orange-400',
        [AuditEventType.CACHED_RESULT_USED]: 'bg-cyan-500/10 text-cyan-400',
        [AuditEventType.CONTEXT_WINDOW_PRUNED]: 'bg-purple-500/10 text-purple-400',
        [AuditEventType.VAULT_SECRET_ADDED]: 'bg-green-500/10 text-green-500',
        [AuditEventType.VAULT_SECRET_UPDATED]: 'bg-yellow-500/10 text-yellow-400',
        [AuditEventType.VAULT_SECRET_DELETED]: 'bg-red-500/10 text-red-400',
        [AuditEventType.VAULT_SECRET_VIEWED]: 'bg-sky-500/10 text-sky-400',
        [AuditEventType.LLM_GATEWAY_STATUS_CHANGED]: 'bg-indigo-500/10 text-indigo-400',
        [AuditEventType.LLM_MODEL_CHANGED]: 'bg-fuchsia-500/10 text-fuchsia-400',
        [AuditEventType.AGENT_MODE_CHANGED]: 'bg-teal-500/10 text-teal-400',
        [AuditEventType.DOCUMENT_INDEXED]: 'bg-lime-500/10 text-lime-400',
    };
    return (
        <span className={`px-2 py-1 text-xs font-semibold rounded-full ${typeStyles[type]}`}>
            {type.replace(/_/g, ' ')}
        </span>
    );
};

const ReportModal: React.FC<{ report: ComplianceReport; onClose: () => void }> = ({ report, onClose }) => (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4">
        <div className="bg-secondary rounded-lg border border-gray-700 shadow-xl max-w-4xl w-full h-[90vh] flex flex-col">
            <header className="p-4 border-b border-gray-700 flex justify-between items-center">
                <h3 className="text-lg font-bold text-white">Compliance Report</h3>
                <button onClick={onClose} className="text-gray-400 hover:text-white">&times;</button>
            </header>
            <div className="p-6 flex-1 overflow-y-auto">
                <p className="text-sm text-gray-400">Generated By: {report.generatedBy.name} at {new Date(report.generatedAt).toLocaleString()}</p>
                <p className="text-sm text-gray-400">Reporting Period: {new Date(report.period.start).toLocaleString()} to {new Date(report.period.end).toLocaleString()}</p>
                <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
                    <div className="bg-surface p-3 rounded-lg"><p className="text-xs text-gray-400">Total Events</p><p className="text-xl font-bold">{report.summary.totalEvents}</p></div>
                    <div className="bg-surface p-3 rounded-lg"><p className="text-xs text-gray-400">Tool Calls</p><p className="text-xl font-bold">{report.summary.toolCalls}</p></div>
                    <div className="bg-surface p-3 rounded-lg"><p className="text-xs text-gray-400">Security Alerts</p><p className="text-xl font-bold">{report.summary.securityAlerts}</p></div>
                    <div className="bg-surface p-3 rounded-lg"><p className="text-xs text-gray-400">Approvals</p><p className="text-xl font-bold">{report.summary.approvals}</p></div>
                </div>
                <div className="mt-6">
                    <h4 className="text-md font-semibold text-white mb-2">Detailed Log</h4>
                    <pre className="text-xs bg-background p-4 rounded-md overflow-x-auto h-96">{JSON.stringify(report.log, null, 2)}</pre>
                </div>
            </div>
            <footer className="p-4 border-t border-gray-700 text-right">
                <button onClick={onClose} className="bg-primary text-white px-4 py-2 rounded-lg text-sm font-medium">Close</button>
            </footer>
        </div>
    </div>
);


export const AuditView: React.FC<AuditViewProps> = ({ auditLog, currentUser }) => {
    const [report, setReport] = useState<ComplianceReport | null>(null);
    const sortedLog = useMemo(() => [...auditLog].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()), [auditLog]);
    
    const stats = useMemo(() => {
        return {
            totalEvents: auditLog.length,
            toolCalls: auditLog.filter(e => e.type === AuditEventType.TOOL_CALL_INITIATED).length,
            securityAlerts: auditLog.filter(e => e.type === AuditEventType.SECURITY_ALERT).length,
            approvals: auditLog.filter(e => e.type === AuditEventType.APPROVAL_DECISION).length,
        };
    }, [auditLog]);

    const handleGenerateReport = () => {
        if (currentUser.role === Role.MANAGER) {
            const generatedReport = generateComplianceReport(auditLog, currentUser);
            setReport(generatedReport);
        }
    };

    return (
        <div className="flex flex-col h-full bg-background p-6">
            {report && <ReportModal report={report} onClose={() => setReport(null)} />}
            <header className="mb-6 flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-bold text-white">Audit Dashboard</h2>
                    <p className="text-md text-gray-400">Monitor all agent and user activities.</p>
                </div>
                {currentUser.role === Role.MANAGER && (
                    <button 
                        onClick={handleGenerateReport}
                        disabled={auditLog.length === 0}
                        className="bg-primary text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-500 disabled:bg-gray-500 disabled:cursor-not-allowed">
                        Generate Compliance Report
                    </button>
                )}
            </header>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-6">
                <StatCard title="Total Events" value={stats.totalEvents} icon={<ChartBarIcon className="w-6 h-6 text-accent"/>} />
                <StatCard title="Tool Calls" value={stats.toolCalls} icon={<ToolsIcon className="w-6 h-6 text-accent"/>} />
                <StatCard title="Security Alerts" value={stats.securityAlerts} icon={<WarningIcon className="w-6 h-6 text-accent"/>} />
                <StatCard title="Approvals Processed" value={stats.approvals} icon={<ShieldCheckIcon className="w-6 h-6 text-accent"/>} />
            </div>

            <div className="flex-1 bg-surface rounded-lg border border-gray-700 flex flex-col overflow-hidden">
                <h3 className="p-4 text-lg font-semibold text-white border-b border-gray-700">Event Log</h3>
                <div className="flex-1 overflow-y-auto">
                    {sortedLog.length === 0 ? (
                        <div className="text-center p-8 text-gray-500">No events logged yet.</div>
                    ) : (
                        <table className="w-full text-sm text-left text-gray-300">
                            <thead className="text-xs text-gray-400 uppercase bg-gray-800 sticky top-0">
                                <tr>
                                    <th scope="col" className="px-6 py-3">Timestamp</th>
                                    <th scope="col" className="px-6 py-3">User</th>
                                    <th scope="col" className="px-6 py-3">Event Type</th>
                                    <th scope="col" className="px-6 py-3">Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                {sortedLog.map(event => (
                                    <tr key={event.id} className="border-b border-gray-700 hover:bg-gray-700/50">
                                        <td className="px-6 py-4 whitespace-nowrap">{new Date(event.timestamp).toLocaleString()}</td>
                                        <td className="px-6 py-4">{event.user.name}</td>
                                        <td className="px-6 py-4"><EventTypePill type={event.type} /></td>
                                        <td className="px-6 py-4 font-mono text-xs">{JSON.stringify(event.details)}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    )}
                </div>
            </div>
        </div>
    );
};